from __future__ import annotations

import os
from pathlib import Path

import mlflow
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MLFLOW_DB = (PROJECT_ROOT / "mlflow.db").as_posix()
MLFLOW_TRACKING_URI = os.getenv("MLFLOW_TRACKING_URI", f"sqlite:///{DEFAULT_MLFLOW_DB}")
REGISTERED_MODEL_NAME = os.getenv("MLFLOW_REGISTERED_MODEL_NAME", "lab28-fallback-llm")


class FallbackLLMModel(mlflow.pyfunc.PythonModel):
    def predict(self, context, model_input):
        rows = len(model_input) if hasattr(model_input, "__len__") else 1
        return ["Fallback response generated by Lab28 local model registry artifact."] * rows


def register_model() -> str:
    mlflow.set_tracking_uri(MLFLOW_TRACKING_URI)
    mlflow.set_experiment("lab28-platform")
    with mlflow.start_run(run_name="register-fallback-llm") as run:
        mlflow.log_param("serving_backend", "vLLM on Kaggle with local fallback")
        mlflow.log_param("fallback_enabled", True)
        mlflow.log_metric("smoke_latency_budget_ms", 2000)
        mlflow.set_tag("integration_point", "MLflow -> Model Registry")
        mlflow.set_tag("model_role", "fallback_when_kaggle_unavailable")
        sample_input = pd.DataFrame({"query": ["What is platform engineering?"]})
        mlflow.pyfunc.log_model(
            artifact_path="fallback_llm",
            python_model=FallbackLLMModel(),
            input_example=sample_input,
        )
        model_uri = f"runs:/{run.info.run_id}/fallback_llm"
        try:
            mlflow.register_model(model_uri=model_uri, name=REGISTERED_MODEL_NAME)
            print(f"Registered model: {REGISTERED_MODEL_NAME}")
        except Exception as exc:
            print(f"Model metadata logged. Registry creation skipped: {exc}")
        print(f"Integration 6 OK: MLflow tracking URI = {MLFLOW_TRACKING_URI}")
        print(f"Model URI: {model_uri}")
        return model_uri


if __name__ == "__main__":
    register_model()
